language: ruby
rvm:
- 2.2.5

install: gem install jekyll

script: jekyll build

env:
  global:  # Ignore YAMLLintBear because indentation required
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Ignore YAMLLintBear
sudo: false
